trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'Lib.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
  fetchDepth: 0

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '-c Release -p:Publish=true'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/artifacts'
    contents: '*.nupkg'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: packages