pr:
- develop

trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  buildSolution: 'source\Lib.sln'
  buildConfiguration: 'Release'
  testSolution: 'test\Test.sln'  
  testConfiguration: 'Test'

stages:
- stage: build
  displayName: Build
  jobs:
  - job: build
    steps:
    - checkout: self
      fetchDepth: 0
      fetchTags: true

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: '-c $(buildConfiguration)'    
        projects: $(buildSolution)

- stage: test
  dependsOn: build
  displayName: Test
  jobs:
  - job: test
    steps:
    - checkout: self
      fetchDepth: 0
      fetchTags: true

    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        arguments: '-c $(testConfiguration)'    
        projects: $(testSolution)