pr:
- develop

trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'Lib.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
  fetchDepth: 0
  fetchTags: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '-c Release'
