// <copyright file="UIXmlns.cs" author="Dmitry Kravchenin" email="d.kravchenin@zaaml.com">
//   Copyright (c) zaaml. All rights reserved.
// </copyright>

using System.Windows.Markup;

[assembly: XmlnsPrefix("http://schemas.zaaml.com/xaml", "zm")]

[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Data")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Windows")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Decorators")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.AccordionView")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.BreadCrumb")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.BackstageView")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.TabView")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.Editors")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.Editors.Text")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.Editors.DropDown")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.Core")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.Core.Compatibility")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.Menu")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.ScrollView")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.SplitView")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.Primitives")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.Primitives.ContentPrimitives")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.Primitives.PopupPrimitives")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.Primitives.TextPrimitives")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.Primitives.SharedSizePrimitives")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.Primitives.TrackBar")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Panels")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Panels.Core")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Panels.Primitives")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Panels.Flexible")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Panels.Native")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Panels.TablePanel")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.ToolBar")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.ValidationSummary")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.ListView")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.TableView")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.TreeView")]
[assembly: XmlnsDefinition("http://schemas.zaaml.com/xaml", "Zaaml.UI.Controls.DropDown")]