
// <copyright file="ExpressionEngine.Register.cs" author="Dmitry Kravchenin" email="d.kravchenin@zaaml.com">
//   Copyright (c) Zaaml. All rights reserved.
// </copyright>

// *************************************************************
//
// AutoGenerated
//
// *************************************************************

// ReSharper disable All

using System;

namespace Zaaml.Expressions
{
	internal partial class ExpressionEngine
	{
		public void RegisterMethod<TResult>(string name, Func<TResult> func)
		{
			RegisterMethodImpl(name, func);
		}
		public void RegisterMethod<TArg1, TResult>(string name, Func<TArg1, TResult> func)
		{
			RegisterMethodImpl(name, func);
		}
		public void RegisterMethod<TArg1, TArg2, TResult>(string name, Func<TArg1, TArg2, TResult> func)
		{
			RegisterMethodImpl(name, func);
		}
		public void RegisterMethod<TArg1, TArg2, TArg3, TResult>(string name, Func<TArg1, TArg2, TArg3, TResult> func)
		{
			RegisterMethodImpl(name, func);
		}
		public void RegisterMethod<TArg1, TArg2, TArg3, TArg4, TResult>(string name, Func<TArg1, TArg2, TArg3, TArg4, TResult> func)
		{
			RegisterMethodImpl(name, func);
		}
		public void RegisterMethod<TArg1, TArg2, TArg3, TArg4, TArg5, TResult>(string name, Func<TArg1, TArg2, TArg3, TArg4, TArg5, TResult> func)
		{
			RegisterMethodImpl(name, func);
		}
		public void RegisterMethod<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TResult>(string name, Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TResult> func)
		{
			RegisterMethodImpl(name, func);
		}
		public void RegisterMethod<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TResult>(string name, Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TResult> func)
		{
			RegisterMethodImpl(name, func);
		}
		public void RegisterMethod<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TResult>(string name, Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TResult> func)
		{
			RegisterMethodImpl(name, func);
		}
		public void RegisterMethod<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TResult>(string name, Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TResult> func)
		{
			RegisterMethodImpl(name, func);
		}
		public void RegisterMethod<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TResult>(string name, Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TResult> func)
		{
			RegisterMethodImpl(name, func);
		}
		public void RegisterMethod<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TResult>(string name, Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TResult> func)
		{
			RegisterMethodImpl(name, func);
		}
		public void RegisterMethod<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TResult>(string name, Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TResult> func)
		{
			RegisterMethodImpl(name, func);
		}
		public void RegisterMethod<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TResult>(string name, Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TResult> func)
		{
			RegisterMethodImpl(name, func);
		}
		public void RegisterMethod<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TResult>(string name, Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TResult> func)
		{
			RegisterMethodImpl(name, func);
		}
		public void RegisterMethod<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15, TResult>(string name, Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15, TResult> func)
		{
			RegisterMethodImpl(name, func);
		}
		public void RegisterMethod<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15, TArg16, TResult>(string name, Func<TArg1, TArg2, TArg3, TArg4, TArg5, TArg6, TArg7, TArg8, TArg9, TArg10, TArg11, TArg12, TArg13, TArg14, TArg15, TArg16, TResult> func)
		{
			RegisterMethodImpl(name, func);
		}
	}
}