name: Release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0      
      
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x    
    
    - name: Clean
      run: dotnet clean source/Lib.sln -c Release && dotnet nuget locals all --clear
    
    - name: Build
      run: dotnet build source/Lib.sln -c Release -p:Publish=true

    - name: Push packages to nuget.org
      run: dotnet nuget push artifacts/**/*.nupkg --api-key ${{ secrets.NUGET_ZAAML }} --source https://api.nuget.org/v3/index.json
      
    - name: Upload workflow artifact
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: artifacts/

    - name: Zip nuget packages
      run: powershell Compress-Archive -Path ./artifacts/*.nupkg -DestinationPath ./artifacts/packages.zip -Force
                  
    - name: Upload release artifact
      uses: actions/upload-release-asset@v1.0.2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: artifacts/packages.zip
        asset_name: packages.zip
        asset_content_type: application/zip

